services:
  - type: web
    name: stock-warroom
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: Referrer-Policy
        value: no-referrer
    routes:
      - type: rewrite
        source: /
        destination: /index.html
